### ISSUE TITLE
cannot generate configuration on ubuntu 16.04/14.04 and Debian8 x86_64

### ISSUE THREAD

**Issue by AceSlash** [coova/coova-chilli#323]
Hello,

Similar issue as #263 and #116 (I don't understand why those tickets are closed by the way).

When chilli is installed, it creates a script `/etc/init.d/chilli` that should be used to create the configuration files (if I understand correctly), but this script depends on `/etc/rc.d/init.d/functions` which is not present on Debian/Ubuntu systems:

```
# /etc/init.d/chilli start
/etc/init.d/chilli: 9: .: Can't open /etc/rc.d/init.d/functions
```

I created an ansible role to reproduce it:
```
---
# file: roles/coova_chilli/tasks/main.yml

- name: "package for build"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - automake
    - autoconf
    - libtool
    - gengetopt
    - haserl
    - libssl-dev
    - freeradius-utils
    - git
  tags: coova_chilli

- name: "git clone"
  git:
    repo: https://github.com/coova/coova-chilli.git
    dest: /usr/local/src/coova-chilli
  register: git
  tags: coova_chilli

- name: "./bootstrap"
  command: './bootstrap chdir="/usr/local/src/coova-chilli"'
  when: git.changed == True
  tags: coova_chilli

# from https://www.howtoforge.com/tutorial/how-to-install-a-wireless-hotspot-with-captive-page-in-linux-using-coovachilli/
- name: "./configure --prefix=/usr --libdir=/usr/lib64 --localstatedir=/var --sysconfdir=/etc --enable-miniportal --with-openssl --enable-libjson --enable-useragent --enable-sessionstate --enable-sessionid --enable-chilliredir --enable-binstatusfile --enable-statusfile --disable-static --enable-shared --enable-largelimits --enable-proxyvsa --enable-chilliproxy --enable-chilliradsec --with-poll"
  command: './configure --prefix=/usr --libdir=/usr/lib64 --localstatedir=/var --sysconfdir=/etc --enable-miniportal --with-openssl --enable-libjson --enable-useragent --enable-sessionstate --enable-sessionid --enable-chilliredir --enable-binstatusfile --enable-statusfile --disable-static --enable-shared --enable-largelimits --enable-proxyvsa --enable-chilliproxy --enable-chilliradsec --with-poll chdir="/usr/local/src/coova-chilli"'
  when: git.changed == True
  tags: coova_chilli

- name: "make"
  command: 'make chdir="/usr/local/src/coova-chilli"'
  when: git.changed == True
  tags: coova_chilli

- name: "make install"
  command: 'make install chdir="/usr/local/src/coova-chilli"'
  when: git.changed == True
  tags: coova_chilli
```
Seems to me like coova-chilli cannot be used easily on modern Debian Family based systems, does this not qualify as a bug? Or is coova-chilli not supported on this type of distrib?
